import Navbar from '@/components/Navbar';

export default function TermsOfService() {
    return (
        <div className="flex min-h-screen flex-col bg-white dark:bg-neutral-950 transition-colors duration-300">
            <Navbar />
            <main className="flex-1 container mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8">
                <div className="prose prose-blue dark:prose-invert max-w-none">
                    <h1>Terms of Service</h1>
                    <p className="text-sm text-neutral-500">Last Updated: {new Date().toLocaleDateString()}</p>

                    <section className="mt-8">
                        <h2>1. Data Ownership & Transparency</h2>
                        <ul>
                            <li><strong>User Consent:</strong> By using &quot;Sign in with X&quot; to authenticate with Xmonials, you explicitly grant Xmonials permission to read your mention timeline and fetch tweets referencing your account on your behalf.</li>
                            <li><strong>No Selling Data:</strong> Xmonials operates strictly as a moderation and display utility. We explicitly do not sell, trade, or rent raw X data, user metadata, or any platform analytics to third parties.</li>
                            <li><strong>Right to Erasure:</strong> Xmonials provides a &quot;Delete Account&quot; functional requirement. Invoking this permanently wipes all cached tweets, user records, and your OAuth tokens from our Supabase database immediately.</li>
                        </ul>
                    </section>

                    <section className="mt-8">
                        <h2>2. Display Standards (Widget Rules)</h2>
                        <p>
                            To ensure compliance with X’s visual requirements and Developer Policy, every testimonial theme or widget generated by Xmonials complies with the following rules:
                        </p>
                        <ul>
                            <li><strong>Identity:</strong> The author’s display name and @handle must be, and are, visibly rendered on every testimonial card.</li>
                            <li><strong>Source Attribution:</strong> A visible X logo or icon is present on every card (or via standard visual motifs) to properly attribute the content to the X platform.</li>
                            <li><strong>The &quot;Link Back&quot;:</strong> Every tweet card serves as a clickable link—or contains a direct timestamp link—that navigates the user directly back to the original post on X.</li>
                            <li><strong>Real-time Accuracy:</strong> If a tweet you have approved on Xmonials is subsequently deleted or made private on X by its author, it may automatically be removed from your Xmonials wall to reflect the true, current state of the content on X.</li>
                        </ul>
                    </section>

                    <section className="mt-8">
                        <h2>3. Usage Restrictions</h2>
                        <ul>
                            <li><strong>No Reselling:</strong> You may not copy, sub-license, resell, or distribute your Xmonials access, your widget API endpoints, or your account privileges to other unaffiliated organizations.</li>
                            <li><strong>Non-Commercial Abuse:</strong> Users are strictly prohibited from using Xmonials to display &quot;coordinated inauthentic behavior,&quot; spam, hate speech, or content designed to manipulate public conversation. Violating this will result in immediate termination of the widget.</li>
                            <li><strong>Rate Limit Awareness:</strong> Due to X&apos;s external API constraints, please be aware that if your account experiences an extreme, sudden surge in mentions (going viral), there may be a delay in our edge functions syncing these new mentions to your dashboard inbox.</li>
                        </ul>
                    </section>
                </div>
            </main>
        </div>
    );
}
